# Generated by Django 4.0.2 on 2023-01-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('content', models.CharField(default='', max_length=255)),
                ('blog_image', models.ImageField(default='', upload_to='documents/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
