# Generated by Django 4.0.2 on 2023-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
