# Generated by Django 4.0.2 on 2023-01-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
    ]
